#pragma once

using namespace ATL;

template <class T>
class CProxy_ILEIEvents : public IConnectionPointImpl<T, &__uuidof( _ILEIEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
